#include "nsISupports.idl"

[scriptable, uuid(895f6166-d106-44c0-a6c0-4b5cbccd9b27)]
interface nsIMafMhtDecoderContentHandler : nsISupports
{
    void onContentStart(in wstring contentType, in wstring contentId, in wstring contentLocation);
    void onContent(in wstring data);
    void onBinaryContent(in wstring data);
    void onContentComplete();
};
