#include "nsISupports.idl"
#include "nsILocalFile.idl"
#include "nsIURL.idl"

[scriptable, uuid(6e08b6a2-7d43-4cc8-90fc-4fe468a41b93)]
interface nsIMafUtil : nsISupports
{
  wstring appendToDir(in wstring initialDir, in wstring subDir);
  nsILocalFile createDir(in wstring dirName);
  void createFile(in wstring fileToCreate, in wstring contents);
  void createExecutableFile(in wstring fileToCreate, in wstring contents);

  void copyBinaryFile(in wstring source, in wstring dest);

  void deleteFile(in wstring fileToDelete);
  boolean checkFileExists(in wstring filePathToCheck);
  wstring getUniqueFilename(in wstring destDir, in wstring suggestedFilename);
  wstring getFullUniqueFilename(in wstring suggestedPathAndFilename);
  wstring readFile(in wstring filename);

  nsISupports readBinaryFile(in wstring filename);

  /* nsIRDFRemoteDataSource */
  nsISupports createRDF(in wstring path, in wstring filename);

  wstring getURI(in nsILocalFile file);
  wstring getURIFromFilename(in wstring filename);

  void addStringData(in nsISupports datasource, in wstring name, in wstring value);
  void openListInTabs(in nsISupports urlList, in nsISupports oBrowser);

  short getNumberOfOpenWindows();
  boolean isWindowOpen(in wstring location);
  wstring addBaseHref(in wstring source, in wstring baseURL);
  wstring getMIMETypeForURI(in wstring url);

  wstring getDefaultFileName(in wstring aDefaultFileName, in nsIURL aDocumentURI);
  wstring validateFileName(in wstring aFileName);
  wstring getExtensionByType(in wstring contentType);

};
