#include "nsISupports.idl"

[scriptable, uuid(5cba4706-ec80-416f-b1e3-2724a023f996)]
interface nsIMafPreferencesRec : nsISupports
{
    attribute string id;
    attribute string archivescript;
    attribute string extractscript;

    short getExtensionsLength();
    string getExtensionAt(in short index);
    void addExtension(in string newExtension);
    void updateExtensionAt(in short index, in string newExtension);
    void removeExtensionAt(in short index);
};
