#include "nsISupports.idl"

[scriptable, uuid(de7a59d9-4857-4a8e-9455-61e1c990d6ea)]
interface nsIMafState : nsISupports
{
  void addArchiveInfo(in wstring tempPath, in wstring foldernum, in wstring archivePath, out PRUint32 count, [array, size_is(count)] out wstring localUrls);
  nsISupports getDatasource();
  boolean isArchiveURL(in wstring url);
  boolean isLocallyMappableURL(in wstring url);
  wstring getLocalURL(in wstring url);
  wstring getOriginalURL(in wstring url);
  boolean isArchiveURIOpen(in wstring url);
  wstring expandedArchiveURIPath(in wstring url);
};
