#include "nsISupports.idl"

[scriptable, uuid(53898f06-03f1-4473-b3a5-9b0008b83b2f)]
interface nsIMaf : nsISupports
{
  void extractFromArchive(in wstring program, in wstring archivefile, in wstring destpath);
  void archiveDownload(in wstring program, in wstring archivefile, in wstring sourcepath);
  void saveAsWebPageComplete(in nsISupports aBrowser, in wstring tempPath, in wstring scriptPath, in wstring archivePath);
  void nativeSaveFile(in nsISupports aDocument, in wstring aSaveDocPath, in wstring aSaveDocFileName, in nsISupports aObjMafArchiver);
  void saveAllTabsComplete(in nsISupports browsers, in wstring includeList, in wstring tempPath, in wstring scriptPath, in wstring archivePath);
  void openFromArchive(in wstring tempPath, in wstring scriptPath, in wstring archivePath);
  void openListInTabs(in nsISupports urlList);
};
