#include "nsISupports.idl"
#include "nsIFile.idl"
#include "nsIURL.idl"
#include "nsISimpleEnumerator.idl"
#include "nsIMafMhtDecoderContentHandler.idl"

[scriptable, uuid(3814ca79-30bc-4ad3-a005-488f05a1dd87)]
interface nsIMafMhtDecoder : nsISupports
{
    readonly attribute wstring PROGID;

    void initWithFile(in nsIFile file);
    void initWithURL(in nsIURL url);
    void init(in wstring content);

    nsISimpleEnumerator getHeaders();
    wstring getHeaderValue(in wstring headerName);

    short noOfParts();
    nsIMafMhtDecoder getPartNo(in short index);
    short rootPartNo();

    void getContent(in nsIMafMhtDecoderContentHandler callback);

    wstring decodeQuotedPrintableString(in string source);
};
