#include "nsISupports.idl"
#include "nsIMaf.idl"
#include "nsIMafProgressUpdater.idl"

[scriptable, uuid(29c494d1-6f42-4ddd-a831-ea2176753ddd)]
interface nsIMafArchiver : nsISupports
{
  attribute short downloadPercentComplete;
  attribute wstring indexfilename;
  attribute boolean downloadComplete;

  void init(in nsISupports aBrowser, in wstring tempPath, in wstring scriptPath, in wstring archivePath, in wstring folderNumber, in nsIMaf maf);
  void start();
  void onDownloadComplete();
  void setProgressUpdater(in nsIMafProgressUpdater updater);
};
