#include "nsISupports.idl"

[scriptable, uuid(5cba4706-ec80-416f-b1e3-2724a023f996)]
interface nsIMafPreferencesRec : nsISupports
{
    attribute wstring id;
    attribute wstring archivescript;
    attribute wstring extractscript;

    short getExtensionsLength();
    wstring getExtensionAt(in short index);
    void addExtension(in wstring newExtension);
    void updateExtensionAt(in short index, in wstring newExtension);
    void removeExtensionAt(in short index);
};
