#include "nsISupports.idl"
#include "nsIFile.idl"

[scriptable, uuid(1a5c8698-b7a4-44af-87f4-38831fb369df)]
interface nsIMafMhtEncoder : nsISupports
{
    readonly attribute wstring PROGID;
    attribute wstring from;
    attribute wstring subject;
    attribute wstring date;

    void addFile(in wstring source, in wstring type, in wstring location, in wstring id);
    void encodeTo(in nsIFile dest);
    string encodeQuotedPrintableString(in wstring source);
};
