#include "nsISupports.idl"
#include "nsISimpleEnumerator.idl"

[scriptable, uuid(7c151e22-e215-4c06-aa5b-a02e3c7a989d)]
interface nsIMafMhtDecoderPart : nsISupports
{
    nsISimpleEnumerator headerNames();
    string getHeaderValue(in string headerName);

    string content();
};
